### ISSUE TITLE
List between 5-10 heuristics for finding candidate papers.

### ISSUE THREAD

**Issue by jorgeramirez** [TrentoCrowdAI/find-similar-papers#4]
Create this list and describe briefly what each heuristic does.

**Comment by fmauri90** [comment]
[Scienstein_A_Research_Paper_Recommender_System.pdf](https://github.com/TrentoCrowdAI/find-similar-papers/files/3713315/Scienstein_A_Research_Paper_Recommender_System.pdf)
[ActiveCite_An_Interactive_System_for_Automatic_Citation.pdf](https://github.com/TrentoCrowdAI/find-similar-papers/files/3713316/ActiveCite_An_Interactive_System_for_Automatic


In these two articles the authors expose the problems of research based on citations, on keywords and on authors. 

Problem with citation:
- there are citations that marginally speak of the topics of the paper. Sometimes the authors insert other articles written by them to advertise themselves

Problem with keywords:
- each keyword has synonyms and this means that there may be papers that are not taken into consideration only because there are no keywords but only their synonyms

Problem with authors:
- the problem in finding similar articles based on the author is that it is possible to find papers that are not related to the author in question but to his homograph

**Comment by fmauri90** [comment]
Euristic for finding candidate papers:
- Collaborative-Based Technique in other words see which papers were most searched after reading the main paper
- research similar paper taking into consideration the papers in the same magazine
- research similar paper in two phases: in the first phase based on citations and in the second phase based which papers were most searched after reading the main paper
